{{/*apiVersion: networking.istio.io/v1alpha3*/}}
{{/*kind: Gateway*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "truemark.fullname" . }}*/}}
{{/*  labels:*/}}
{{/*    {{- include "truemark.labels" . | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  selector:*/}}
{{/*    app: istio-gateway-external*/}}
{{/*  servers:*/}}
{{/*  {{- toYaml .Values.istio.externalGateway.servers | nindent 2 }}*/}}
{{/*---*/}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "truemark.fullname" . }}
spec:
  hosts:
    - {{ .Values.istio.hosts }}
  gateways:
    - {{ include "truemark.fullname" . }}
  http:
  - name: {{ include "truemark.fullname" . }}
    route:
    - destination:
        host: {{ include "truemark.fullname" . }}
        port:
          number: {{ .Values.service.port }}
