---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "truemark.fullname" . }}
spec:
  hosts:
    - "hello.stage.truemark.io"
  gateways:
    - {{ include "truemark.fullname" . }}
  http:
  - name: {{ include "truemark.fullname" . }}
    route:
    - destination:
        host: {{ include "truemark.fullname" . }}
        port:
          number: {{ .Values.service.port }}