apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "truemark.fullname" . }}
  labels:
    {{- include "truemark.labels" . | nindent 4 }}
spec:
  selector:
    app: istio-gateway-external
  servers:
    {{- range $server := .Values.istio.externalGateway.servers }}
    - port:
        number: {{ $server.port.number }}
        name: {{ $server.port.name }}
        protocol: {{ $server.port.protocol }}
      {{- if $server.tls }}
      tls:
        {{- toYaml $server.tls | nindent 8 }}
      {{- end }}
      hosts:
        {{- if $server.hosts }}
        {{- toYaml $server.hosts | nindent 8 }}
        {{- else }}
        - "*"
        {{- end }}
    {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "truemark.fullname" . }}
spec:
  hosts:
    {{- if .Values.istio.externalGateway.servers }}
    {{- range $server := .Values.istio.externalGateway.servers }}
    {{- range $host := $server.hosts }}
    - {{ $host | default "*" }}
    {{- end }}
    {{- end }}
    {{- else }}
    - "*"
    {{- end }}
  gateways:
    - {{ include "truemark.fullname" . }}
  http:
    - name: {{ include "truemark.fullname" . }}
      route:
        - destination:
            host: {{ include "truemark.fullname" . }}
            port:
              number: {{ (index .Values.istio.externalGateway.servers 0).port.number }}
