name: ArgoCD Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update values.yaml
        run: |
          cd helm-chart/hello-world
          export IMAGE_TAG=$(cat image-tag.txt)
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml
          sed -i 's|tag:.*|tag: '${IMAGE_TAG}'|' values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml [skip ci]"
          git push
