name: ArgoCD Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-version

      - name: Set New Tag
        id: new-tag
        run: echo "TAG=$(cat docker-version.txt)" >> $GITHUB_ENV

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update Tag in values.yaml
        run: |
          cd helm-chart/hello-world
          yq eval ".image.tag = env(TAG)" -i values.yaml
        env:
          TAG: ${{ env.TAG }}

      - name: Push Updates to values.yaml
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml [skip ci]"
          git push
