on:
  workflow_dispatch:
  push:
    branches:
      - argocd-demo-louie
permissions:
  id-token: write
  contents: write
jobs:
  build-maven:
    name: Build Maven
    uses: ./.github/workflows/build-maven.yml
    with:
      version: 61.${{ github.run_number }}.${{ github.run_attempt }}
      java_version: 21
      java_distribution: "corretto"
  build-docker:
    name: Build Docker
    uses: ./.github/workflows/build-docker.yml
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/')
    with:
      version: 61.${{ github.run_number }}.${{ github.run_attempt }}
      image_name: "truemark/helloworld-java"
    secrets:
      aws_assume_role: ${{ secrets.AWS_ASSUME_ROLE }}
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    needs: [build-maven]
  eks-deploy-prod:
    if: github.ref == 'refs/heads/argocd-demo-louie'
    name: Deploy using ArgoCD
    uses: ./.github/workflows/argo-deploy.yml
    needs: [build-docker]
