on:
  workflow_call:
    secrets:
      aws_assume_role:
        description: "AWS role to assume"
        required: false
      docker_hub_username:
        description: "Docker Hub username"
        required: false
      docker_hub_password:
        description: "Docker Hub password or token"
        required: false
    inputs:
      image_name:
        description: "Name of the image"
        required: true
        type: string
      version:
        description: "Version of the project"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ASSUME_ROLE: ${{ secrets.aws_assume_role }}
      DOCKER_HUB_USERNAME: ${{ secrets.docker_hub_username }}
      DOCKER_HUB_PASSWORD: ${{ secrets.docker_hub_password }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: env.DOCKER_HUB_USERNAME != '' && env.DOCKER_HUB_PASSWORD != ''
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_password }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f Dockerfile \
            -t ${{ inputs.image_name }}:${{ inputs.version }} \
            -t ${{ inputs.image_name }}:latest \
            .
