name: Values Only Deployment

on:
  push:
    paths:
      - 'k8s/values/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        run: |
          UPDATED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Updated files: $UPDATED_FILES"

          if echo "$UPDATED_FILES" | grep -q "k8s/values/prod.yaml"; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "UPDATED_FILE=k8s/values/prod.yaml" >> $GITHUB_ENV
          elif echo "$UPDATED_FILES" | grep -q "k8s/values/stage.yaml"; then
            echo "ENVIRONMENT=stage" >> $GITHUB_ENV
            echo "UPDATED_FILE=k8s/values/stage.yaml" >> $GITHUB_ENV
          elif echo "$UPDATED_FILES" | grep -q "k8s/values/values.yaml"; then
            echo "ENVIRONMENT=shared" >> $GITHUB_ENV
            echo "UPDATED_FILE=k8s/values/values.yaml" >> $GITHUB_ENV
          else
            echo "No matching environment file found"
            exit 1
          fi
          echo "APP_NAME=hello-world" >> $GITHUB_ENV

      - name: Deploy Stage Changes
        if: env.ENVIRONMENT == 'stage'
        uses: ./.github/workflows/values-update.yml
        with:
          environment: ${{ env.ENVIRONMENT }}
          updated_file: ${{ env.UPDATED_FILE }}
          app_name: ${{ env.APP_NAME }}
          cluster: ${{ vars.CLUSTER_NAME }}

      - name: Deploy Prod Changes
        if: env.ENVIRONMENT == 'prod'
        uses: ./.github/workflows/values-update.yml
        with:
          environment: ${{ env.ENVIRONMENT }}
          updated_file: ${{ env.UPDATED_FILE }}
          app_name: ${{ env.APP_NAME }}
          cluster: ${{ vars.CLUSTER_NAME }}
