name: Values Only Update - Prod
on:
  workflow_dispatch:
  push:
    paths:
      - 'k8s/values/prod.yaml'
      - '!.github/**'
    branches:
      - values/prod/*


permissions:
  id-token: write
  contents: write

jobs:
  values-update-stage:
    name: Update Values Only - Prod
    uses: truemark/github-workflows/.github/workflows/values-only-update.yml@argocd-demo
    with:
      app_name: "hello-world"
      environment: "prod"
    secrets:
      app_id: ${{ secrets.RELEASE_BOT_ID }}
      private_key: ${{ secrets.RELEASE_BOT_KEY }}
