name: Receiver Workflow

on:
  workflow_run:
    workflows: [Trigger Workflow]
    types:
      - completed
    branches:
      - main

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Trigger
        run: echo "Receiver workflow triggered"
