name: Values Only Update - Stage
on:
  workflow_dispatch:
  push:
    paths:
      - 'k8s/values/stage.yaml'
      - '!.github/**'
    branches:
      - values/stage/*

permissions:
  id-token: write
  contents: write

jobs:
  values-update-stage:
    name: Update Values Only - Stage
    uses: truemark/github-workflows/.github/workflows/values-only-update.yml@argocd-demo
    with:
      app_name: "hello-world"
      environment: "stage"
    secrets:
      app_id: ${{ secrets.RELEASE_BOT_ID }}
      private_key: ${{ secrets.RELEASE_BOT_KEY }}
