name: Trigger Workflow

on:
  push:
    branches:
      - testing-secondary-workflows

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Complete Successfully
        run: echo "Trigger workflow completed"
